package kr.releasepilot.controlplane.rollout;

import kr.releasepilot.controlplane.audit.AuditTrail;import kr.releasepilot.controlplane.connection.*;import kr.releasepilot.controlplane.environment.*;import kr.releasepilot.controlplane.notification.GithubCheckService;import kr.releasepilot.controlplane.release.*;import org.junit.jupiter.api.Test;import tools.jackson.databind.ObjectMapper;
import java.time.*;import java.util.*;
import static org.assertj.core.api.Assertions.assertThatThrownBy;import static org.mockito.Mockito.*;

class StartRolloutPreflightTests {
 @Test void staleEnvironmentBlocksExternalMutation(){var fixture=fixture(ConnectionStatus.ACTIVE,Instant.parse("2026-09-14T17:00:00Z"),Instant.parse("2026-09-14T23:00:00Z"));assertThatThrownBy(()->fixture.handler.handle(fixture.command)).isInstanceOf(IllegalStateException.class).hasMessage("ENVIRONMENT_VALIDATION_STALE");verifyNoInteractions(fixture.secrets,fixture.argo);}
 @Test void inactiveClusterBlocksExternalMutation(){var fixture=fixture(ConnectionStatus.INVALID,Instant.parse("2026-09-14T23:00:00Z"),Instant.parse("2026-09-14T23:00:00Z"));assertThatThrownBy(()->fixture.handler.handle(fixture.command)).isInstanceOf(IllegalStateException.class).hasMessage("CLUSTER_CONNECTION_NOT_ACTIVE");verifyNoInteractions(fixture.secrets,fixture.argo);}
 @Test void staleClusterValidationBlocksExternalMutation(){var fixture=fixture(ConnectionStatus.ACTIVE,Instant.parse("2026-09-14T23:00:00Z"),Instant.parse("2026-09-14T17:00:00Z"));assertThatThrownBy(()->fixture.handler.handle(fixture.command)).isInstanceOf(IllegalStateException.class).hasMessage("CLUSTER_CONNECTION_VALIDATION_STALE");verifyNoInteractions(fixture.secrets,fixture.argo);}
 @Test void inactivePrometheusBlocksExternalMutation(){var fixture=fixture(ConnectionStatus.ACTIVE,Instant.parse("2026-09-14T23:00:00Z"),Instant.parse("2026-09-14T23:00:00Z"),ConnectionStatus.INVALID,Instant.parse("2026-09-14T23:00:00Z"));assertThatThrownBy(()->fixture.handler.handle(fixture.command)).isInstanceOf(IllegalStateException.class).hasMessage("PROMETHEUS_CONNECTION_NOT_ACTIVE");verifyNoInteractions(fixture.secrets,fixture.argo);}
 @Test void stalePrometheusValidationBlocksExternalMutation(){var fixture=fixture(ConnectionStatus.ACTIVE,Instant.parse("2026-09-14T23:00:00Z"),Instant.parse("2026-09-14T23:00:00Z"),ConnectionStatus.ACTIVE,Instant.parse("2026-09-14T17:00:00Z"));assertThatThrownBy(()->fixture.handler.handle(fixture.command)).isInstanceOf(IllegalStateException.class).hasMessage("PROMETHEUS_CONNECTION_VALIDATION_STALE");verifyNoInteractions(fixture.secrets,fixture.argo);}
 private Fixture fixture(ConnectionStatus clusterStatus,Instant environmentValidatedAt,Instant clusterValidatedAt){return fixture(clusterStatus,environmentValidatedAt,clusterValidatedAt,ConnectionStatus.ACTIVE,Instant.parse("2026-09-14T23:00:00Z"));}
 private Fixture fixture(ConnectionStatus clusterStatus,Instant environmentValidatedAt,Instant clusterValidatedAt,ConnectionStatus prometheusStatus,Instant prometheusValidatedAt){var now=Instant.parse("2026-09-15T00:00:00Z");var executions=mock(RolloutExecutionRepository.class);var releases=mock(ReleaseRepository.class);var artifacts=mock(ReleaseArtifactRepository.class);var environments=mock(EnvironmentRepository.class);var clusters=mock(ClusterConnectionRepository.class);var prometheus=mock(PrometheusConnectionRepository.class);var secrets=mock(SecretResolver.class);var argo=mock(ArgoRolloutsGateway.class);var steps=mock(RolloutStepRepository.class);var release=Release.pending(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"1","change","a".repeat(40),"https://ci","request-key",now);var artifact=ReleaseArtifact.create(release.getId(),"registry/app","sha256:"+"b".repeat(64));var prometheusConnection=PrometheusConnection.create("prometheus","https://prom.example",null,10,now);prometheusConnection.validated(prometheusStatus,prometheusValidatedAt);var env=Environment.create(release.getServiceId(),"production",UUID.randomUUID(),"demo","app","app","stable","canary",prometheusConnection.getId(),"app=x",UUID.randomUUID(),now);env.complete(false,false,environmentValidatedAt);var cluster=ClusterConnection.create("cluster","https://k.example",List.of("demo"),"env:TOKEN",now);cluster.validated(clusterStatus,clusterValidatedAt);var execution=RolloutExecution.pending(release.getId(),cluster.getId(),"demo","app",artifact.getImageDigest(),now);when(executions.findById(execution.getId())).thenReturn(Optional.of(execution));when(releases.findById(release.getId())).thenReturn(Optional.of(release));when(artifacts.findByReleaseId(release.getId())).thenReturn(Optional.of(artifact));when(environments.findById(release.getEnvironmentId())).thenReturn(Optional.of(env));when(clusters.findById(execution.getClusterId())).thenReturn(Optional.of(cluster));when(prometheus.findById(env.getPrometheusConnectionId())).thenReturn(Optional.of(prometheusConnection));var handler=new StartRolloutCommandHandler(executions,releases,artifacts,environments,clusters,prometheus,secrets,argo,steps,mock(AuditTrail.class),new ObjectMapper(),Clock.fixed(now,ZoneOffset.UTC),mock(GithubCheckService.class),Duration.ofHours(6),Duration.ofHours(6));return new Fixture(handler,secrets,argo,new RolloutCommandHandler.Command(UUID.randomUUID(),execution.getId(),UUID.randomUUID(),"START_ROLLOUT","{}",1));}
 private record Fixture(StartRolloutCommandHandler handler,SecretResolver secrets,ArgoRolloutsGateway argo,RolloutCommandHandler.Command command){}
}
