package kr.releasepilot.controlplane.approval;
import kr.releasepilot.controlplane.audit.*;import kr.releasepilot.controlplane.catalog.*;import kr.releasepilot.controlplane.connection.*;import kr.releasepilot.controlplane.environment.*;import kr.releasepilot.controlplane.identity.*;import kr.releasepilot.controlplane.release.*;import kr.releasepilot.controlplane.rollout.RolloutDispatchService;import kr.releasepilot.controlplane.shared.error.*;
import org.springframework.beans.factory.annotation.Value;import org.springframework.security.core.Authentication;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Clock;import java.time.Duration;import java.util.UUID;
import kr.releasepilot.controlplane.notification.GithubCheckService;
@Service public class ApprovalService{
 private final ReleaseRepository releases;private final ApprovalDecisionRepository decisions;private final EnvironmentRepository environments;private final ClusterConnectionRepository clusters;private final PrometheusConnectionRepository prometheus;private final CatalogServiceRepository services;private final ProjectAccess access;private final AuditTrail audits;private final RolloutDispatchService rolloutDispatch;private final Clock clock;private final GithubCheckService githubChecks;private final Duration environmentValidationMaxAge;private final Duration connectionValidationMaxAge;
 public ApprovalService(ReleaseRepository releases,ApprovalDecisionRepository decisions,EnvironmentRepository environments,ClusterConnectionRepository clusters,PrometheusConnectionRepository prometheus,CatalogServiceRepository services,ProjectAccess access,AuditTrail audits,RolloutDispatchService rolloutDispatch,Clock clock,GithubCheckService githubChecks,@Value("${releasepilot.environment-revalidation.max-age:PT6H}")Duration environmentValidationMaxAge,@Value("${releasepilot.connection-validation.max-age:PT6H}")Duration connectionValidationMaxAge){this.releases=releases;this.decisions=decisions;this.environments=environments;this.clusters=clusters;this.prometheus=prometheus;this.services=services;this.access=access;this.audits=audits;this.rolloutDispatch=rolloutDispatch;this.clock=clock;this.githubChecks=githubChecks;this.environmentValidationMaxAge=environmentValidationMaxAge;this.connectionValidationMaxAge=connectionValidationMaxAge;}
 @Transactional public Release decide(UUID releaseId,ApprovalDecision.Decision decision,String reason,String key,UserAccountPrincipal actor,Authentication authentication){
  var retried=decisions.findByDecidedByAndIdempotencyKey(actor.id(),key);if(retried.isPresent()){var prior=retried.get();if(prior.getDecision()!=decision||!prior.getReleaseId().equals(releaseId))throw new ConflictException("IDEMPOTENCY_KEY_REUSED","Idempotency key was used for another decision");return releases.findById(releaseId).orElseThrow(()->new NotFoundException("RELEASE_NOT_FOUND","Release not found"));}
  var release=releases.findById(releaseId).orElseThrow(()->new NotFoundException("RELEASE_NOT_FOUND","Release not found"));var catalog=services.findById(release.getServiceId()).orElseThrow();if(!access.hasRole(catalog.getProjectId(),authentication,Role.APPROVER))throw new NotFoundException("RELEASE_NOT_FOUND","Release not found");
  var env=environments.findById(release.getEnvironmentId()).orElseThrow();if("production".equals(env.getName())&&release.getRequestedBy().equals(actor.id()))throw new ConflictException("SELF_APPROVAL_NOT_ALLOWED","Requester cannot decide their own production release");
  if(release.getStatus()!=ReleaseStatus.PENDING_APPROVAL)throw new ConflictException("RELEASE_NOT_PENDING_APPROVAL","Release is not pending approval");
  var now=clock.instant();if(decision==ApprovalDecision.Decision.APPROVED){if(env.getStatus()!=EnvironmentStatus.ACTIVE&&env.getStatus()!=EnvironmentStatus.ACTIVE_WITH_WARNINGS)throw new ConflictException("ENVIRONMENT_NOT_ACTIVE","Environment must pass validation before approval");if(env.getValidatedAt()==null||!env.getValidatedAt().isAfter(now.minus(environmentValidationMaxAge)))throw new ConflictException("ENVIRONMENT_VALIDATION_STALE","Environment validation has expired; revalidate before approval");var cluster=clusters.findById(env.getClusterId()).orElseThrow(()->new NotFoundException("CLUSTER_CONNECTION_NOT_FOUND","Cluster connection not found"));if(cluster.getStatus()!=ConnectionStatus.ACTIVE)throw new ConflictException("CLUSTER_CONNECTION_NOT_ACTIVE","Target cluster connection must pass validation before approval");if(cluster.getLastValidatedAt()==null||!cluster.getLastValidatedAt().isAfter(now.minus(connectionValidationMaxAge)))throw new ConflictException("CLUSTER_CONNECTION_VALIDATION_STALE","Target cluster validation has expired; revalidate before approval");var prometheusConnection=prometheus.findById(env.getPrometheusConnectionId()).orElseThrow(()->new NotFoundException("PROMETHEUS_CONNECTION_NOT_FOUND","Prometheus connection not found"));if(prometheusConnection.getStatus()!=ConnectionStatus.ACTIVE)throw new ConflictException("PROMETHEUS_CONNECTION_NOT_ACTIVE","Target Prometheus connection must pass validation before approval");if(prometheusConnection.getLastValidatedAt()==null||!prometheusConnection.getLastValidatedAt().isAfter(now.minus(connectionValidationMaxAge)))throw new ConflictException("PROMETHEUS_CONNECTION_VALIDATION_STALE","Target Prometheus validation has expired; revalidate before approval");release.approve(now);rolloutDispatch.schedule(release,env,now);githubChecks.approved(releaseId,release.getVersion());}else{release.reject(now);githubChecks.completed(releaseId,release.getVersion(),false,"rejected");}decisions.save(ApprovalDecision.create(releaseId,actor.id(),decision,reason,key,now));audits.record(AuditEvent.releaseDecision(releaseId,actor.id(),decision.name(),now));return release;}
}
