package kr.releasepilot.controlplane.approval;
import kr.releasepilot.controlplane.audit.*;import kr.releasepilot.controlplane.catalog.*;import kr.releasepilot.controlplane.environment.*;import kr.releasepilot.controlplane.identity.*;import kr.releasepilot.controlplane.release.*;import kr.releasepilot.controlplane.rollout.RolloutDispatchService;import kr.releasepilot.controlplane.shared.error.*;
import org.springframework.security.core.Authentication;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Clock;import java.util.UUID;
@Service public class ApprovalService{
 private final ReleaseRepository releases;private final ApprovalDecisionRepository decisions;private final EnvironmentRepository environments;private final CatalogServiceRepository services;private final ProjectAccess access;private final AuditEventRepository audits;private final RolloutDispatchService rolloutDispatch;private final Clock clock;
 public ApprovalService(ReleaseRepository releases,ApprovalDecisionRepository decisions,EnvironmentRepository environments,CatalogServiceRepository services,ProjectAccess access,AuditEventRepository audits,RolloutDispatchService rolloutDispatch,Clock clock){this.releases=releases;this.decisions=decisions;this.environments=environments;this.services=services;this.access=access;this.audits=audits;this.rolloutDispatch=rolloutDispatch;this.clock=clock;}
 @Transactional public Release decide(UUID releaseId,ApprovalDecision.Decision decision,String reason,String key,UserAccountPrincipal actor,Authentication authentication){
  var retried=decisions.findByDecidedByAndIdempotencyKey(actor.id(),key);if(retried.isPresent()){var prior=retried.get();if(prior.getDecision()!=decision||!prior.getReleaseId().equals(releaseId))throw new ConflictException("IDEMPOTENCY_KEY_REUSED","Idempotency key was used for another decision");return releases.findById(releaseId).orElseThrow(()->new NotFoundException("RELEASE_NOT_FOUND","Release not found"));}
  var release=releases.findById(releaseId).orElseThrow(()->new NotFoundException("RELEASE_NOT_FOUND","Release not found"));var catalog=services.findById(release.getServiceId()).orElseThrow();if(!access.hasRole(catalog.getProjectId(),authentication,Role.APPROVER))throw new NotFoundException("RELEASE_NOT_FOUND","Release not found");
  var env=environments.findById(release.getEnvironmentId()).orElseThrow();if("production".equals(env.getName())&&release.getRequestedBy().equals(actor.id()))throw new ConflictException("SELF_APPROVAL_NOT_ALLOWED","Requester cannot decide their own production release");
  if(release.getStatus()!=ReleaseStatus.PENDING_APPROVAL)throw new ConflictException("RELEASE_NOT_PENDING_APPROVAL","Release is not pending approval");
  var now=clock.instant();if(decision==ApprovalDecision.Decision.APPROVED){release.approve(now);rolloutDispatch.schedule(release,env,now);}else release.reject(now);decisions.save(ApprovalDecision.create(releaseId,actor.id(),decision,reason,key,now));audits.save(AuditEvent.releaseDecision(releaseId,actor.id(),decision.name(),now));return release;}
}
