package kr.releasepilot.controlplane.rollout;
import kr.releasepilot.controlplane.audit.*;import kr.releasepilot.controlplane.release.*;import kr.releasepilot.controlplane.shared.error.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tools.jackson.databind.ObjectMapper;import java.time.*;import java.util.UUID;
@Service public class RolloutOperationService{
 private final ReleaseRepository releases;private final RolloutExecutionRepository executions;private final OutboxCommandRepository commands;private final AuditEventRepository audits;private final ObjectMapper json;private final Clock clock;
 public RolloutOperationService(ReleaseRepository releases,RolloutExecutionRepository executions,OutboxCommandRepository commands,AuditEventRepository audits,ObjectMapper json,Clock clock){this.releases=releases;this.executions=executions;this.commands=commands;this.audits=audits;this.json=json;this.clock=clock;}
 @Transactional public Receipt request(UUID releaseId,ArgoRolloutsGateway.Action action,String reason,String key,UUID actorId){var release=releases.findById(releaseId).orElseThrow(()->new NotFoundException("RELEASE_NOT_FOUND","Release not found"));var execution=executions.findByReleaseId(releaseId).orElseThrow(()->new ConflictException("ROLLOUT_EXECUTION_NOT_FOUND","Release has no rollout execution"));var existing=commands.findByIdempotencyKey(key);if(existing.isPresent()){if(!existing.get().getAggregateId().equals(execution.getId())||!existing.get().getCommandType().equals(action.name()+"_ROLLOUT"))throw new ConflictException("IDEMPOTENCY_KEY_REUSED","Idempotency key was used for another operation");return new Receipt(existing.get().getId(),releaseId,"ACCEPTED",existing.get().getAvailableAt());}validate(release,action);try{String type=action.name()+"_ROLLOUT";String payload=json.writeValueAsString(new Payload(releaseId,actorId,reason));var now=clock.instant();var saved=commands.save(OutboxCommand.operation(execution,type,key,payload,now));audits.save(AuditEvent.rolloutOperation(releaseId,actorId,"REQUESTED",action.name(),payload,now));return new Receipt(saved.getId(),releaseId,"ACCEPTED",now);}catch(Exception e){throw new IllegalStateException(e);}}
 private void validate(Release r,ArgoRolloutsGateway.Action a){if((a==ArgoRolloutsGateway.Action.PROMOTE||a==ArgoRolloutsGateway.Action.PAUSE)&&r.getStatus()!=ReleaseStatus.RUNNING)conflict();if(a==ArgoRolloutsGateway.Action.RESUME&&r.getStatus()!=ReleaseStatus.PAUSED)conflict();if(a==ArgoRolloutsGateway.Action.ABORT&&r.getStatus()!=ReleaseStatus.RUNNING&&r.getStatus()!=ReleaseStatus.PAUSED)conflict();}
 private void conflict(){throw new ConflictException("ROLLOUT_OPERATION_NOT_ALLOWED","Operation is not allowed in current release state");}
 public record Payload(UUID releaseId,UUID actorId,String reason){}public record Receipt(UUID operationId,UUID releaseId,String status,Instant acceptedAt){}
}
