package kr.releasepilot.controlplane.rollout;

import kr.releasepilot.controlplane.audit.*;import kr.releasepilot.controlplane.connection.*;
import kr.releasepilot.controlplane.environment.*;
import kr.releasepilot.controlplane.release.*;
import kr.releasepilot.controlplane.notification.GithubCheckService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import java.time.Clock;import java.time.Duration;

@Component
public class StartRolloutCommandHandler implements RolloutCommandHandler {
    private final RolloutExecutionRepository executions; private final ReleaseRepository releases;
    private final ReleaseArtifactRepository artifacts; private final EnvironmentRepository environments;
    private final ClusterConnectionRepository clusters;private final PrometheusConnectionRepository prometheus; private final SecretResolver secrets;private final Duration environmentValidationMaxAge;private final Duration connectionValidationMaxAge;
    private final ArgoRolloutsGateway argo;private final RolloutStepRepository steps;private final AuditTrail audits;private final tools.jackson.databind.ObjectMapper json; private final Clock clock;private final GithubCheckService githubChecks;
    public StartRolloutCommandHandler(RolloutExecutionRepository executions,ReleaseRepository releases,ReleaseArtifactRepository artifacts,EnvironmentRepository environments,ClusterConnectionRepository clusters,PrometheusConnectionRepository prometheus,SecretResolver secrets,ArgoRolloutsGateway argo,RolloutStepRepository steps,AuditTrail audits,tools.jackson.databind.ObjectMapper json,Clock clock,GithubCheckService githubChecks,@Value("${releasepilot.environment-revalidation.max-age:PT6H}")Duration environmentValidationMaxAge,@Value("${releasepilot.connection-validation.max-age:PT6H}")Duration connectionValidationMaxAge){this.executions=executions;this.releases=releases;this.artifacts=artifacts;this.environments=environments;this.clusters=clusters;this.prometheus=prometheus;this.secrets=secrets;this.argo=argo;this.steps=steps;this.audits=audits;this.json=json;this.clock=clock;this.githubChecks=githubChecks;this.environmentValidationMaxAge=environmentValidationMaxAge;this.connectionValidationMaxAge=connectionValidationMaxAge;}
    @Override @Transactional public void handle(Command command){
        var execution=executions.findById(command.executionId()).orElseThrow();var release=releases.findById(execution.getReleaseId()).orElseThrow();
        var artifact=artifacts.findByReleaseId(release.getId()).orElseThrow();var env=environments.findById(release.getEnvironmentId()).orElseThrow();
        var cluster=clusters.findById(execution.getClusterId()).orElseThrow();
        if("START_ROLLOUT".equals(command.type())){var now=clock.instant();var prometheusConnection=prometheus.findById(env.getPrometheusConnectionId()).orElseThrow();validateStartPreflight(env,cluster,prometheusConnection,now);var secret=secrets.resolve(cluster.getSecretRef()).orElseThrow(()->new IllegalStateException("CLUSTER_SECRET_UNAVAILABLE"));var observed=argo.start(new ArgoRolloutsGateway.StartRequest(cluster.getApiServer(),secret.bearerToken(),execution.getNamespace(),execution.getRolloutName(),env.getContainerName(),artifact.getImageRepository()+"@"+artifact.getImageDigest()));execution.started(observed.uid(),observed.resourceVersion(),now);release.running();var rolloutSteps=steps.findByExecutionIdOrderByStepIndexAsc(execution.getId());if(!rolloutSteps.isEmpty()&&rolloutSteps.getFirst().getStatus()==RolloutStepStatus.PENDING)rolloutSteps.getFirst().start(now);return;}
        var secret=secrets.resolve(cluster.getSecretRef()).orElseThrow(()->new IllegalStateException("CLUSTER_SECRET_UNAVAILABLE"));
        ArgoRolloutsGateway.Action action=switch(command.type()){case "PROMOTE_ROLLOUT"->ArgoRolloutsGateway.Action.PROMOTE;case "PAUSE_ROLLOUT"->ArgoRolloutsGateway.Action.PAUSE;case "RESUME_ROLLOUT"->ArgoRolloutsGateway.Action.RESUME;case "ABORT_ROLLOUT"->ArgoRolloutsGateway.Action.ABORT;default->throw new IllegalArgumentException("Unsupported rollout command: "+command.type());};
        if(execution.getRolloutUid()==null)throw new IllegalStateException("Rollout execution UID is unavailable");var now=clock.instant();var observed=argo.control(new ArgoRolloutsGateway.ControlRequest(cluster.getApiServer(),secret.bearerToken(),execution.getNamespace(),execution.getRolloutName(),execution.getRolloutUid(),action));if(action==ArgoRolloutsGateway.Action.PROMOTE){var rolloutSteps=steps.findByExecutionIdOrderByStepIndexAsc(execution.getId());int current=execution.getCurrentStepIndex();if(current>=rolloutSteps.size())throw new IllegalStateException("No Canary step is available for promotion");rolloutSteps.get(current).pass(now);if(current+1<rolloutSteps.size())rolloutSteps.get(current+1).start(now);}execution.controlled(action,observed.resourceVersion(),now);release.controlled(action,now);if(action==ArgoRolloutsGateway.Action.ABORT)githubChecks.completed(release.getId(),release.getVersion(),false,"aborted");try{var payload=json.readValue(command.payloadJson(),RolloutOperationService.Payload.class);audits.record(AuditEvent.rolloutOperation(release.getId(),payload.actorId(),"SUCCEEDED",action.name(),json.writeValueAsString(java.util.Map.of("reason",payload.reason(),"resourceVersion",observed.resourceVersion())),now));}catch(Exception e){throw new IllegalStateException("Cannot record rollout operation audit",e);}
    }
    private void validateStartPreflight(Environment env,ClusterConnection cluster,PrometheusConnection prometheusConnection,java.time.Instant now){if(env.getStatus()!=EnvironmentStatus.ACTIVE&&env.getStatus()!=EnvironmentStatus.ACTIVE_WITH_WARNINGS)throw new IllegalStateException("ENVIRONMENT_NOT_ACTIVE");if(env.getValidatedAt()==null||env.getValidatedAt().isBefore(now.minus(environmentValidationMaxAge)))throw new IllegalStateException("ENVIRONMENT_VALIDATION_STALE");if(cluster.getStatus()!=ConnectionStatus.ACTIVE)throw new IllegalStateException("CLUSTER_CONNECTION_NOT_ACTIVE");if(cluster.getLastValidatedAt()==null||cluster.getLastValidatedAt().isBefore(now.minus(connectionValidationMaxAge)))throw new IllegalStateException("CLUSTER_CONNECTION_VALIDATION_STALE");if(prometheusConnection.getStatus()!=ConnectionStatus.ACTIVE)throw new IllegalStateException("PROMETHEUS_CONNECTION_NOT_ACTIVE");if(prometheusConnection.getLastValidatedAt()==null||prometheusConnection.getLastValidatedAt().isBefore(now.minus(connectionValidationMaxAge)))throw new IllegalStateException("PROMETHEUS_CONNECTION_VALIDATION_STALE");}
}
