package kr.releasepilot.controlplane.analysis;
import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;
@Entity @Table(name="analysis_jobs") public class AnalysisJob{
 @Id private UUID id;@Column(name="step_id",nullable=false,unique=true)private UUID stepId;@Column(name="correlation_id")private UUID correlationId;@Enumerated(EnumType.STRING)@Column(nullable=false,length=20)private AnalysisJobStatus status;@Column(nullable=false)private int attempts;@Column(name="max_attempts",nullable=false)private int maxAttempts;@Column(name="available_at",nullable=false)private Instant availableAt;@Column(name="claimed_at")private Instant claimedAt;@Column(name="window_start",nullable=false)private Instant windowStart;@Column(name="window_end",nullable=false)private Instant windowEnd;@Enumerated(EnumType.STRING)@Column(length=20)private AnalysisVerdict verdict;@Column(name="reason_code",length=60)private String reasonCode;@org.hibernate.annotations.JdbcTypeCode(org.hibernate.type.SqlTypes.JSON) @Column(name="evidence_json",columnDefinition="json")private String evidenceJson;@Column(name="last_error",length=2000)private String lastError;@Column(name="created_at",nullable=false,updatable=false)private Instant createdAt;@Column(name="completed_at")private Instant completedAt;@Version private long version;protected AnalysisJob(){}
 public static AnalysisJob pending(UUID stepId,UUID correlationId,int maxAttempts,Instant start,Instant end){var j=new AnalysisJob();j.id=UUID.randomUUID();j.stepId=stepId;j.correlationId=correlationId;j.status=AnalysisJobStatus.PENDING;j.maxAttempts=maxAttempts;j.availableAt=end;j.windowStart=start;j.windowEnd=end;j.createdAt=end;return j;}
 public UUID getId(){return id;}public UUID getStepId(){return stepId;}public UUID getCorrelationId(){return correlationId;}public int getAttempts(){return attempts;}public int getMaxAttempts(){return maxAttempts;}public Instant getWindowStart(){return windowStart;}public Instant getWindowEnd(){return windowEnd;}public AnalysisJobStatus getStatus(){return status;}public AnalysisVerdict getVerdict(){return verdict;}public String getReasonCode(){return reasonCode;}public String getEvidenceJson(){return evidenceJson;}
 public void claim(Instant now){if(status!=AnalysisJobStatus.PENDING&&status!=AnalysisJobStatus.RETRY_WAIT)throw new IllegalStateException("Job is not dispatchable");status=AnalysisJobStatus.PROCESSING;attempts++;claimedAt=now;lastError=null;}
 public void retry(String error,Instant next){if(status!=AnalysisJobStatus.PROCESSING)throw new IllegalStateException("Job is not processing");status=AnalysisJobStatus.RETRY_WAIT;availableAt=next;windowEnd=next;claimedAt=null;lastError=truncate(error);}
 public void complete(AnalysisVerdict verdict,String reason,String evidence,Instant now){if(status!=AnalysisJobStatus.PROCESSING)throw new IllegalStateException("Job is not processing");this.status=AnalysisJobStatus.COMPLETED;this.verdict=verdict;reasonCode=reason;evidenceJson=evidence;completedAt=now;claimedAt=null;}
 public void recover(Instant now){if(status!=AnalysisJobStatus.PROCESSING)throw new IllegalStateException("Job is not processing");status=AnalysisJobStatus.RETRY_WAIT;availableAt=now;claimedAt=null;lastError="Analysis processing lease expired";}
 private String truncate(String value){String v=value==null?"Unknown analysis failure":value;return v.substring(0,Math.min(v.length(),2000));}
}
