apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: releasepilot-demo, namespace: argocd }
spec:
  project: default
  source:
    repoURL: https://github.com/automaster5013/ReleasePilot.git
    targetRevision: main
    path: deploy/overlays/aws-demo
  destination: { server: https://kubernetes.default.svc, namespace: releasepilot }
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: mysql
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]?.status
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
