package kr.releasepilot.controlplane.release;
import kr.releasepilot.controlplane.catalog.*;import kr.releasepilot.controlplane.connection.*;import kr.releasepilot.controlplane.environment.*;import kr.releasepilot.controlplane.identity.*;import kr.releasepilot.controlplane.policy.*;import kr.releasepilot.controlplane.rollout.*;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.core.authority.SimpleGrantedAuthority;import org.springframework.security.test.web.servlet.setup.SecurityMockMvcConfigurers;import org.springframework.test.web.servlet.*;import org.springframework.test.web.servlet.setup.MockMvcBuilders;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.context.WebApplicationContext;
import java.time.Instant;import java.util.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @Transactional class ReleaseRequestApiTests {
 @Autowired WebApplicationContext context;@Autowired ProjectRepository projects;@Autowired CatalogServiceRepository services;@Autowired ClusterConnectionRepository clusters;@Autowired PrometheusConnectionRepository prometheus;@Autowired EnvironmentRepository environments;@Autowired UserAccountRepository users;@Autowired ProjectMembershipRepository memberships;@Autowired PolicyRepository policies;@Autowired PolicyVersionRepository versions;@Autowired ReleaseRepository releases;@Autowired ReleaseArtifactRepository artifacts;@Autowired PolicySnapshotRepository snapshots;@Autowired RolloutExecutionRepository executions;@Autowired RolloutStepRepository rolloutSteps;@Autowired OutboxCommandRepository outbox;private MockMvc mvc;
 @BeforeEach void setup(){mvc=MockMvcBuilders.webAppContextSetup(context).apply(SecurityMockMvcConfigurers.springSecurity()).build();}
 @Test void developerCreatesImmutablePendingReleaseAndSecondActiveReleaseIsBlocked()throws Exception{
  var now=Instant.now();var project=projects.save(Project.create("release-test","Release Test",null,now));var app=services.save(CatalogService.create(project.getId(),"checkout","Checkout","https://github.com/acme/checkout","platform",now));
  var user=users.save(UserAccount.create("release-developer","hash","Developer",Set.of(Role.DEVELOPER,Role.APPROVER),now));memberships.save(ProjectMembership.create(project.getId(),user.getId(),Role.APPROVER,now));
  var cluster=clusters.save(ClusterConnection.create("release-cluster","https://kubernetes.example",List.of("demo"),"env:TEST_TOKEN",now));var prom=prometheus.save(PrometheusConnection.create("release-prom","http://prometheus:9090",null,15,now));
  var policy=policies.save(Policy.create("release-policy",now));var policyVersion=PolicyVersion.draft(policy.getId(),1,definition(),"abc",user.getId(),now);policyVersion.activate();versions.save(policyVersion);
  var env=Environment.create(app.getId(),"production",cluster.getId(),"demo","checkout","checkout","checkout-stable","checkout-canary",prom.getId(),"service_name=checkout",policyVersion.getId(),now);env.complete(false,false,now);environments.save(env);
  String body="""
   {"serviceId":"%s","environmentId":"%s","version":"1.2.3","imageRepository":"ghcr.io/acme/checkout","imageDigest":"sha256:%s","changeSummary":"Safer checkout","commitSha":"%s","pipelineUrl":"https://ci.example/runs/1"}
   """.formatted(app.getId(),env.getId(),"a".repeat(64),"b".repeat(40));
  mvc.perform(post("/api/v1/releases").with(authentication(authToken(user,"ROLE_DEVELOPER"))).with(csrf()).header("Idempotency-Key","release-inactive-cluster").contentType(MediaType.APPLICATION_JSON).content(body))
   .andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CLUSTER_CONNECTION_NOT_ACTIVE"));
  cluster.validated(ConnectionStatus.ACTIVE,now);clusters.save(cluster);
  cluster.validated(ConnectionStatus.ACTIVE,now.minusSeconds(25_200));clusters.save(cluster);
  mvc.perform(post("/api/v1/releases").with(authentication(authToken(user,"ROLE_DEVELOPER"))).with(csrf()).header("Idempotency-Key","release-stale-cluster").contentType(MediaType.APPLICATION_JSON).content(body))
   .andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CLUSTER_CONNECTION_VALIDATION_STALE"));
  cluster.validated(ConnectionStatus.ACTIVE,Instant.now());clusters.save(cluster);
  mvc.perform(post("/api/v1/releases").with(authentication(authToken(user,"ROLE_DEVELOPER"))).with(csrf()).header("Idempotency-Key","release-inactive-prometheus").contentType(MediaType.APPLICATION_JSON).content(body))
   .andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("PROMETHEUS_CONNECTION_NOT_ACTIVE"));
  prom.validated(ConnectionStatus.ACTIVE,now.minusSeconds(25_200));prometheus.save(prom);
  mvc.perform(post("/api/v1/releases").with(authentication(authToken(user,"ROLE_DEVELOPER"))).with(csrf()).header("Idempotency-Key","release-stale-prometheus").contentType(MediaType.APPLICATION_JSON).content(body))
   .andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("PROMETHEUS_CONNECTION_VALIDATION_STALE"));
  prom.validated(ConnectionStatus.ACTIVE,Instant.now());prometheus.save(prom);
  env.complete(false,false,now.minusSeconds(25_200));environments.save(env);
  mvc.perform(post("/api/v1/releases").with(authentication(authToken(user,"ROLE_DEVELOPER"))).with(csrf()).header("Idempotency-Key","release-stale-environment").contentType(MediaType.APPLICATION_JSON).content(body))
   .andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("ENVIRONMENT_VALIDATION_STALE"));
  env.complete(false,false,Instant.now());environments.save(env);
  String approvalKeyPrefix=String.join("-","approval","decision","");
  String response=mvc.perform(post("/api/v1/releases").with(authentication(authToken(user,"ROLE_DEVELOPER"))).with(csrf()).header("Idempotency-Key","release-request-0001").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated()).andExpect(jsonPath("$.status").value("PENDING_APPROVAL")).andExpect(jsonPath("$.imageDigest").value("sha256:"+"a".repeat(64))).andReturn().getResponse().getContentAsString();
  String releaseId=response.substring(response.indexOf("\"id\":\"")+6,response.indexOf("\"",response.indexOf("\"id\":\"")+6));
  org.assertj.core.api.Assertions.assertThat(artifacts.count()).isEqualTo(1);org.assertj.core.api.Assertions.assertThat(snapshots.count()).isEqualTo(1);
  mvc.perform(post("/api/v1/releases").with(authentication(authToken(user,"ROLE_DEVELOPER"))).with(csrf()).header("Idempotency-Key","release-request-0002").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("ACTIVE_RELEASE_EXISTS"));
  mvc.perform(post("/api/v1/releases/{id}/approve",releaseId).with(authentication(authToken(user,"ROLE_APPROVER"))).with(csrf()).header("Idempotency-Key",approvalKeyPrefix+"001").contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"self\"}" )).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("SELF_APPROVAL_NOT_ALLOWED")); // gitleaks:allow -- deterministic test idempotency token
  org.assertj.core.api.Assertions.assertThat(executions.count()).isZero();org.assertj.core.api.Assertions.assertThat(outbox.count()).isZero();
  var approver=users.save(UserAccount.create("release-approver","hash","Approver",Set.of(Role.APPROVER),now));memberships.save(ProjectMembership.create(project.getId(),approver.getId(),Role.APPROVER,now));
  cluster.validated(ConnectionStatus.INVALID,Instant.now());clusters.save(cluster);
  mvc.perform(post("/api/v1/releases/{id}/approve",releaseId).with(authentication(authToken(approver,"ROLE_APPROVER"))).with(csrf()).header("Idempotency-Key",approvalKeyPrefix+"002").contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"checks passed\"}" )).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CLUSTER_CONNECTION_NOT_ACTIVE")); // gitleaks:allow -- deterministic test idempotency token
  cluster.validated(ConnectionStatus.ACTIVE,Instant.now());clusters.save(cluster);
  cluster.validated(ConnectionStatus.ACTIVE,now.minusSeconds(25_200));clusters.save(cluster);
  mvc.perform(post("/api/v1/releases/{id}/approve",releaseId).with(authentication(authToken(approver,"ROLE_APPROVER"))).with(csrf()).header("Idempotency-Key",approvalKeyPrefix+"003").contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"checks passed\"}" )).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CLUSTER_CONNECTION_VALIDATION_STALE")); // gitleaks:allow -- deterministic test idempotency token
  cluster.validated(ConnectionStatus.ACTIVE,Instant.now());clusters.save(cluster);
  prom.validated(ConnectionStatus.INVALID,Instant.now());prometheus.save(prom);
  mvc.perform(post("/api/v1/releases/{id}/approve",releaseId).with(authentication(authToken(approver,"ROLE_APPROVER"))).with(csrf()).header("Idempotency-Key",approvalKeyPrefix+"004").contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"checks passed\"}" )).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("PROMETHEUS_CONNECTION_NOT_ACTIVE")); // gitleaks:allow -- deterministic test idempotency token
  prom.validated(ConnectionStatus.ACTIVE,now.minusSeconds(25_200));prometheus.save(prom);
  mvc.perform(post("/api/v1/releases/{id}/approve",releaseId).with(authentication(authToken(approver,"ROLE_APPROVER"))).with(csrf()).header("Idempotency-Key",approvalKeyPrefix+"005").contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"checks passed\"}" )).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("PROMETHEUS_CONNECTION_VALIDATION_STALE")); // gitleaks:allow -- deterministic test idempotency token
  prom.validated(ConnectionStatus.ACTIVE,Instant.now());prometheus.save(prom);
  env.complete(false,false,now.minusSeconds(25_200));environments.save(env);
  mvc.perform(post("/api/v1/releases/{id}/approve",releaseId).with(authentication(authToken(approver,"ROLE_APPROVER"))).with(csrf()).header("Idempotency-Key",approvalKeyPrefix+"006").contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"checks passed\"}" )).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("ENVIRONMENT_VALIDATION_STALE")); // gitleaks:allow -- deterministic test idempotency token
  env.complete(true,false,Instant.now());environments.save(env);
  mvc.perform(post("/api/v1/releases/{id}/approve",releaseId).with(authentication(authToken(approver,"ROLE_APPROVER"))).with(csrf()).header("Idempotency-Key",approvalKeyPrefix+"007").contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"checks passed\"}" )).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("ENVIRONMENT_NOT_ACTIVE")); // gitleaks:allow -- deterministic test idempotency token
  org.assertj.core.api.Assertions.assertThat(executions.count()).isZero();org.assertj.core.api.Assertions.assertThat(outbox.count()).isZero();
  env.complete(false,false,Instant.now());environments.save(env);
  mvc.perform(post("/api/v1/releases/{id}/approve",releaseId).with(authentication(authToken(approver,"ROLE_APPROVER"))).with(csrf()).header("Idempotency-Key",approvalKeyPrefix+"008").contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"checks passed\"}" )).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("APPROVED")); // gitleaks:allow -- deterministic test idempotency token
  var execution=executions.findByReleaseId(UUID.fromString(releaseId)).orElseThrow();org.assertj.core.api.Assertions.assertThat(execution.getStatus()).isEqualTo(RolloutExecutionStatus.PENDING);org.assertj.core.api.Assertions.assertThat(execution.getTargetRevision()).isEqualTo("sha256:"+"a".repeat(64));org.assertj.core.api.Assertions.assertThat(outbox.findAll()).singleElement().satisfies(command->{org.assertj.core.api.Assertions.assertThat(command.getCommandType()).isEqualTo("START_ROLLOUT");org.assertj.core.api.Assertions.assertThat(command.getStatus()).isEqualTo(OutboxCommandStatus.PENDING);});
  org.assertj.core.api.Assertions.assertThat(rolloutSteps.findByExecutionIdOrderByStepIndexAsc(execution.getId())).singleElement().satisfies(step->{org.assertj.core.api.Assertions.assertThat(step.getTargetWeight()).isEqualTo(100);org.assertj.core.api.Assertions.assertThat(step.getMinimumObservationSeconds()).isEqualTo(30);});
  execution.started("rollout-uid","10",now);releases.findById(UUID.fromString(releaseId)).orElseThrow().running();
  mvc.perform(post("/api/v1/releases/{id}/pause",releaseId).with(authentication(authToken(approver,"ROLE_OPERATOR"))).with(csrf()).header("Idempotency-Key","pause-operation-0001").contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"incident review\"}")).andExpect(status().isAccepted()).andExpect(jsonPath("$.status").value("ACCEPTED"));
  mvc.perform(post("/api/v1/releases/{id}/pause",releaseId).with(authentication(authToken(approver,"ROLE_OPERATOR"))).with(csrf()).header("Idempotency-Key","pause-operation-0001").contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"incident review\"}")).andExpect(status().isAccepted());org.assertj.core.api.Assertions.assertThat(outbox.count()).isEqualTo(2);
  mvc.perform(get("/api/v1/releases/{id}",releaseId).with(authentication(authToken(approver,"ROLE_APPROVER")))).andExpect(status().isOk())
   .andExpect(jsonPath("$.imageRepository").value("ghcr.io/acme/checkout")).andExpect(jsonPath("$.context.serviceName").value("Checkout")).andExpect(jsonPath("$.context.environmentName").value("production"))
   .andExpect(jsonPath("$.requester.displayName").value("Developer")).andExpect(jsonPath("$.requester.username").value("release-developer"))
   .andExpect(jsonPath("$.policySnapshot.sourcePolicyVersionId").value(policyVersion.getId().toString())).andExpect(jsonPath("$.policySnapshot.definition.strategy").value("CANARY")).andExpect(jsonPath("$.policySnapshot.definition.metrics[0].threshold").value(0.01))
   .andExpect(jsonPath("$.approval.reason").value("checks passed"));
  var privateProject=projects.save(Project.create("private-release","Private Release",null,now));var privateService=services.save(CatalogService.create(privateProject.getId(),"private-app","Private App","https://github.com/acme/private","platform",now));
  var privateRelease=releases.save(Release.pending(privateService.getId(),UUID.randomUUID(),user.getId(),"9.9.9","private","c".repeat(40),"https://ci.example/private","private-release-key",now.plusSeconds(10)));artifacts.save(ReleaseArtifact.create(privateRelease.getId(),"ghcr.io/acme/private","sha256:"+"d".repeat(64)));
  mvc.perform(get("/api/v1/releases").param("limit","1").with(authentication(authToken(approver,"ROLE_APPROVER")))).andExpect(status().isOk()).andExpect(jsonPath("$.items.length()").value(1)).andExpect(jsonPath("$.items[0].id").value(releaseId)).andExpect(jsonPath("$.items[0].context.serviceName").value("Checkout")).andExpect(jsonPath("$.items[0].context.environmentName").value("production"));
  mvc.perform(get("/api/v1/audit-events").param("aggregateType","RELEASE").param("aggregateId",releaseId).with(authentication(authToken(approver,"ROLE_APPROVER")))).andExpect(status().isOk()).andExpect(jsonPath("$.items.length()").value(3)).andExpect(jsonPath("$.items[0].payloadJson").doesNotExist());
 }
 private UsernamePasswordAuthenticationToken authToken(UserAccount u,String role){var p=new UserAccountPrincipal(u.getId(),u.getUsername(),"hash",u.getDisplayName(),true,List.of(new SimpleGrantedAuthority(role)));return UsernamePasswordAuthenticationToken.authenticated(p,p.getPassword(),p.getAuthorities());}
 private String definition(){return "{\"schemaVersion\":\"1.0\",\"strategy\":\"CANARY\",\"steps\":[{\"weight\":100,\"minimumObservationSeconds\":30}],\"metrics\":[{\"key\":\"HTTP_5XX_RATE\",\"required\":true,\"threshold\":0.01},{\"key\":\"HTTP_P95_LATENCY_MS\",\"required\":true,\"threshold\":500},{\"key\":\"REQUEST_COUNT\",\"required\":true,\"threshold\":1000}]}";}
}
