apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: releasepilot
resources: [../../base, ingress.yaml, issuer.yaml, network-policy.yaml, storage-class.yaml]
images:
  - name: control-plane
    newName: 327771416502.dkr.ecr.ap-northeast-2.amazonaws.com/releasepilot/control-plane
    digest: sha256:96a0db5712c0c8ec2442659df00ee1c44f507c95899f6755616ed806778e28e9
  - name: analysis-worker
    newName: 327771416502.dkr.ecr.ap-northeast-2.amazonaws.com/releasepilot/analysis-worker
    digest: sha256:4da4e1c8408d8f1f15cfa2bcebfd6561143f4f3776e3d4ea781bb37b5e3eb23b
  - name: web-console
    newName: 327771416502.dkr.ecr.ap-northeast-2.amazonaws.com/releasepilot/web-console
    digest: sha256:e8f72b264d52e96f889ba0827faa42db7ca29d2a8eb18e01c33038d488f722a0
patches:
  - target: { kind: Rollout }
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value: { releasepilot.kr/release: v0.51.0 }
  - target: { kind: Rollout, name: control-plane }
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: AUDIT_ARCHIVE_ENABLED, value: "true" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: AUDIT_ARCHIVE_PROVIDER, value: "s3" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: AUDIT_ARCHIVE_S3_BUCKET, value: "releasepilot-demo-audit-327771416502" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: AWS_REGION, value: "ap-northeast-2" }
