apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: releasepilot
resources: [../../base, ingress.yaml, issuer.yaml, network-policy.yaml, storage-class.yaml]
images:
  - name: control-plane
    newName: 327771416502.dkr.ecr.ap-northeast-2.amazonaws.com/releasepilot/control-plane
    digest: sha256:035fc030ebee55f17e5efab4a22f64c150b1e906af3108130a0969c1f48b93f2
  - name: analysis-worker
    newName: 327771416502.dkr.ecr.ap-northeast-2.amazonaws.com/releasepilot/analysis-worker
    digest: sha256:58750c9065577fe7a698c3dab2316e302c2118294ebf2396eaf136c756ecc9c9
  - name: web-console
    newName: 327771416502.dkr.ecr.ap-northeast-2.amazonaws.com/releasepilot/web-console
    digest: sha256:082a056944895e51315421289c0f3dadfd928ea3aec47b5e3015690311b73f18
patches:
  - target: { kind: Rollout }
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value: { releasepilot.kr/release: v0.39.0 }
  - target: { kind: Rollout, name: control-plane }
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: AUDIT_ARCHIVE_ENABLED, value: "true" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: AUDIT_ARCHIVE_PROVIDER, value: "s3" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: AUDIT_ARCHIVE_S3_BUCKET, value: "releasepilot-demo-audit-327771416502" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: AWS_REGION, value: "ap-northeast-2" }
