apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: releasepilot
resources: [../../base, ingress.yaml, issuer.yaml, network-policy.yaml, storage-class.yaml]
images:
  - name: control-plane
    newName: automaster5013/releasepilot-control-plane
    digest: sha256:e72f3b04d339008fed69f946c40ff4d9a19ad330062cd1f0ccc42243ff1f4f03
  - name: analysis-worker
    newName: automaster5013/releasepilot-analysis-worker
    digest: sha256:fd4be0435d941939a6fe4285cabefe92f8722137c300bc5183d5a449a0bdcf29
  - name: web-console
    newName: automaster5013/releasepilot-web-console
    digest: sha256:38edd6a8b3bd42103e091b93de1e7510c146cec03ef0c6dd1e79875e4c9727f5
patches:
  - target: { kind: Rollout, name: control-plane }
    path: connector-credentials.yaml
  - target: { kind: Rollout }
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value: { releasepilot.kr/release: v0.52.0 }
  - target: { kind: Rollout, name: control-plane }
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: AUDIT_ARCHIVE_ENABLED, value: "true" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: AUDIT_ARCHIVE_PROVIDER, value: "s3" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: AUDIT_ARCHIVE_S3_BUCKET, value: "releasepilot-demo-audit-327771416502" }
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: { name: AWS_REGION, value: "ap-northeast-2" }
