package kr.releasepilot.controlplane.release;
import kr.releasepilot.controlplane.catalog.*;import kr.releasepilot.controlplane.environment.*;import kr.releasepilot.controlplane.identity.*;import kr.releasepilot.controlplane.policy.*;import kr.releasepilot.controlplane.shared.error.*;
import org.springframework.beans.factory.annotation.Value;import org.springframework.security.core.Authentication;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tools.jackson.databind.ObjectMapper;import java.time.Clock;import java.time.Duration;import java.util.UUID;
import kr.releasepilot.controlplane.audit.*;
import kr.releasepilot.controlplane.notification.GithubCheckService;
import kr.releasepilot.controlplane.connection.*;
@Service public class ReleaseRequestService {
 private final ReleaseRepository releases;private final ReleaseArtifactRepository artifacts;private final PolicySnapshotRepository snapshots;private final EnvironmentRepository environments;private final ClusterConnectionRepository clusters;private final PrometheusConnectionRepository prometheus;private final CatalogServiceRepository services;private final PolicyVersionRepository policies;private final ProjectAccess access;private final AuditTrail auditEvents;private final ObjectMapper json;private final Clock clock;private final GithubCheckService githubChecks;private final Duration environmentValidationMaxAge;private final Duration connectionValidationMaxAge;
 public ReleaseRequestService(ReleaseRepository releases,ReleaseArtifactRepository artifacts,PolicySnapshotRepository snapshots,EnvironmentRepository environments,ClusterConnectionRepository clusters,PrometheusConnectionRepository prometheus,CatalogServiceRepository services,PolicyVersionRepository policies,ProjectAccess access,AuditTrail auditEvents,ObjectMapper json,Clock clock,GithubCheckService githubChecks,@Value("${releasepilot.environment-revalidation.max-age:PT6H}")Duration environmentValidationMaxAge,@Value("${releasepilot.connection-validation.max-age:PT6H}")Duration connectionValidationMaxAge){this.releases=releases;this.artifacts=artifacts;this.snapshots=snapshots;this.environments=environments;this.clusters=clusters;this.prometheus=prometheus;this.services=services;this.policies=policies;this.access=access;this.auditEvents=auditEvents;this.json=json;this.clock=clock;this.githubChecks=githubChecks;this.environmentValidationMaxAge=environmentValidationMaxAge;this.connectionValidationMaxAge=connectionValidationMaxAge;}
 @Transactional public Result create(Command c,UserAccountPrincipal actor,Authentication authentication){
  var existing=releases.findByRequestedByAndIdempotencyKey(actor.id(),c.idempotencyKey());if(existing.isPresent()){var release=existing.get();return new Result(release,artifacts.findByReleaseId(release.getId()).orElseThrow());}
  var env=environments.findById(c.environmentId()).orElseThrow(()->new NotFoundException("ENVIRONMENT_NOT_FOUND","Environment not found"));if(!env.getServiceId().equals(c.serviceId()))throw new ConflictException("ENVIRONMENT_SERVICE_MISMATCH","Environment does not belong to service");
  var catalog=services.findById(c.serviceId()).orElseThrow(()->new NotFoundException("SERVICE_NOT_FOUND","Service not found"));if(!access.hasRole(catalog.getProjectId(),authentication,Role.DEVELOPER))throw new NotFoundException("PROJECT_NOT_FOUND","Project not found");
  if(env.getStatus()!=EnvironmentStatus.ACTIVE&&env.getStatus()!=EnvironmentStatus.ACTIVE_WITH_WARNINGS)throw new ConflictException("ENVIRONMENT_NOT_ACTIVE","Environment must pass validation before release request");
  if(env.getValidatedAt()==null||!env.getValidatedAt().isAfter(clock.instant().minus(environmentValidationMaxAge)))throw new ConflictException("ENVIRONMENT_VALIDATION_STALE","Environment validation has expired; revalidate before release request");
  var cluster=clusters.findById(env.getClusterId()).orElseThrow(()->new NotFoundException("CLUSTER_CONNECTION_NOT_FOUND","Cluster connection not found"));
  if(cluster.getStatus()!=ConnectionStatus.ACTIVE)throw new ConflictException("CLUSTER_CONNECTION_NOT_ACTIVE","Target cluster connection must pass validation before release request");
  if(cluster.getLastValidatedAt()==null||!cluster.getLastValidatedAt().isAfter(clock.instant().minus(connectionValidationMaxAge)))throw new ConflictException("CLUSTER_CONNECTION_VALIDATION_STALE","Target cluster validation has expired; revalidate before release request");
  var prometheusConnection=prometheus.findById(env.getPrometheusConnectionId()).orElseThrow(()->new NotFoundException("PROMETHEUS_CONNECTION_NOT_FOUND","Prometheus connection not found"));
  if(prometheusConnection.getStatus()!=ConnectionStatus.ACTIVE)throw new ConflictException("PROMETHEUS_CONNECTION_NOT_ACTIVE","Target Prometheus connection must pass validation before release request");
  if(prometheusConnection.getLastValidatedAt()==null||!prometheusConnection.getLastValidatedAt().isAfter(clock.instant().minus(connectionValidationMaxAge)))throw new ConflictException("PROMETHEUS_CONNECTION_VALIDATION_STALE","Target Prometheus validation has expired; revalidate before release request");
  if(releases.existsByEnvironmentIdAndActiveSlotTrue(env.getId()))throw new ConflictException("ACTIVE_RELEASE_EXISTS","An active release already exists for environment");
  UUID policyId=c.requestedPolicyVersionId()==null?env.getDefaultPolicyVersionId():c.requestedPolicyVersionId();var policy=policies.findById(policyId).orElseThrow(()->new NotFoundException("POLICY_VERSION_NOT_FOUND","Policy version not found"));if(policy.getStatus()!=PolicyVersionStatus.ACTIVE)throw new ConflictException("POLICY_VERSION_NOT_ACTIVE","Policy version is not active");
  try{if(!env.getRolloutStrategy().name().equals(json.readTree(policy.getDefinition()).path("strategy").asText()))throw new ConflictException("POLICY_STRATEGY_MISMATCH","Policy strategy does not match environment rollout strategy");}catch(ConflictException e){throw e;}catch(Exception e){throw new ConflictException("POLICY_DEFINITION_INVALID","Policy definition is not valid JSON");}
  var now=clock.instant();var release=releases.save(Release.pending(c.serviceId(),c.environmentId(),actor.id(),c.version(),c.changeSummary(),c.commitSha(),c.pipelineUrl(),c.idempotencyKey(),now));var artifact=artifacts.save(ReleaseArtifact.create(release.getId(),c.imageRepository(),c.imageDigest()));snapshots.save(PolicySnapshot.create(release.getId(),policy.getId(),policy.getDefinition(),policy.getChecksum(),now));auditEvents.record(AuditEvent.releaseRequested(release.getId(),actor.id(),now));githubChecks.requested(release,catalog);return new Result(release,artifact);}
 public record Command(UUID serviceId,UUID environmentId,String version,String imageRepository,String imageDigest,String changeSummary,String commitSha,String pipelineUrl,UUID requestedPolicyVersionId,String idempotencyKey){}public record Result(Release release,ReleaseArtifact artifact){}
}
