package kr.releasepilot.controlplane.release;
import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="releases") public class Release {
 @Id private UUID id;@Column(name="service_id",nullable=false)private UUID serviceId;@Column(name="environment_id",nullable=false)private UUID environmentId;@Column(name="requested_by",nullable=false)private UUID requestedBy;
 @Column(nullable=false,length=100)private String version;@Column(name="change_summary",nullable=false,length=2000)private String changeSummary;@Column(name="commit_sha",nullable=false,length=40)private String commitSha;@Column(name="pipeline_url",nullable=false,length=1000)private String pipelineUrl;
 @Enumerated(EnumType.STRING)@Column(nullable=false,length=30)private ReleaseStatus status;@Column(name="idempotency_key",nullable=false,length=128)private String idempotencyKey;@Column(name="active_slot")private Boolean activeSlot;@Column(name="created_at",nullable=false,updatable=false)private Instant createdAt;@Column(name="approved_at")private Instant approvedAt;@Column(name="finished_at")private Instant finishedAt;protected Release(){}
 public static Release pending(UUID serviceId,UUID environmentId,UUID actor,String version,String summary,String commit,String pipeline,String key,Instant now){var r=new Release();r.id=UUID.randomUUID();r.serviceId=serviceId;r.environmentId=environmentId;r.requestedBy=actor;r.version=version;r.changeSummary=summary;r.commitSha=commit;r.pipelineUrl=pipeline;r.status=ReleaseStatus.PENDING_APPROVAL;r.idempotencyKey=key;r.activeSlot=true;r.createdAt=now;return r;}
 public UUID getId(){return id;}public UUID getServiceId(){return serviceId;}public UUID getEnvironmentId(){return environmentId;}public UUID getRequestedBy(){return requestedBy;}public String getVersion(){return version;}public String getChangeSummary(){return changeSummary;}public String getCommitSha(){return commitSha;}public String getPipelineUrl(){return pipelineUrl;}public ReleaseStatus getStatus(){return status;}public Instant getCreatedAt(){return createdAt;}
 public void approve(Instant now){requirePending();status=ReleaseStatus.APPROVED;approvedAt=now;}public void reject(Instant now){requirePending();status=ReleaseStatus.REJECTED;finishedAt=now;activeSlot=null;}private void requirePending(){if(status!=ReleaseStatus.PENDING_APPROVAL)throw new IllegalStateException("Release is not pending approval");}
 public void running(){if(status!=ReleaseStatus.APPROVED&&status!=ReleaseStatus.RUNNING)throw new IllegalStateException("Release is not approved");status=ReleaseStatus.RUNNING;}
 public void controlled(kr.releasepilot.controlplane.rollout.ArgoRolloutsGateway.Action action,Instant now){if(action==kr.releasepilot.controlplane.rollout.ArgoRolloutsGateway.Action.PROMOTE)return;if(action==kr.releasepilot.controlplane.rollout.ArgoRolloutsGateway.Action.PAUSE)status=ReleaseStatus.PAUSED;else if(action==kr.releasepilot.controlplane.rollout.ArgoRolloutsGateway.Action.RESUME)status=ReleaseStatus.RUNNING;else{status=ReleaseStatus.ABORTED;finishedAt=now;activeSlot=null;}}
 public void succeeded(Instant now){if(status!=ReleaseStatus.RUNNING)throw new IllegalStateException("Release is not running");status=ReleaseStatus.SUCCEEDED;finishedAt=now;activeSlot=null;}
 public void failed(Instant now){if(status==ReleaseStatus.SUCCEEDED||status==ReleaseStatus.ABORTED)return;status=ReleaseStatus.FAILED;finishedAt=now;activeSlot=null;}
 public Instant getApprovedAt(){return approvedAt;}public Instant getFinishedAt(){return finishedAt;}
}
