package kr.releasepilot.controlplane.release;
import kr.releasepilot.controlplane.approval.*;import kr.releasepilot.controlplane.catalog.*;import kr.releasepilot.controlplane.environment.*;import kr.releasepilot.controlplane.identity.*;import kr.releasepilot.controlplane.policy.*;import kr.releasepilot.controlplane.shared.error.NotFoundException;
import org.springframework.data.domain.PageRequest;import org.springframework.security.core.Authentication;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
import tools.jackson.databind.*;
@Service public class ReleaseQueryService{
 private final ReleaseRepository releases;private final ReleaseArtifactRepository artifacts;private final PolicySnapshotRepository snapshots;private final ApprovalDecisionRepository decisions;private final CatalogServiceRepository services;private final EnvironmentRepository environments;private final UserAccountRepository users;private final ProjectAccess access;private final PolicyVersionRepository versions;private final PolicyRepository policies;private final ObjectMapper json;
 public ReleaseQueryService(ReleaseRepository releases,ReleaseArtifactRepository artifacts,PolicySnapshotRepository snapshots,ApprovalDecisionRepository decisions,CatalogServiceRepository services,EnvironmentRepository environments,UserAccountRepository users,ProjectAccess access,PolicyVersionRepository versions,PolicyRepository policies,ObjectMapper json){this.releases=releases;this.artifacts=artifacts;this.snapshots=snapshots;this.decisions=decisions;this.services=services;this.environments=environments;this.users=users;this.access=access;this.versions=versions;this.policies=policies;this.json=json;}
 @Transactional(readOnly=true)public List<Item> list(int limit,Authentication auth){return releases.findAllByOrderByCreatedAtDesc(PageRequest.of(0,limit)).stream().filter(value->allowed(value,auth)).map(this::item).toList();}
 @Transactional(readOnly=true)public Detail detail(UUID id,Authentication auth){var value=releases.findById(id).orElseThrow(this::notFound);if(!allowed(value,auth))throw notFound();var snapshot=snapshots.findByReleaseId(id).orElseThrow();var version=versions.findById(snapshot.getSourcePolicyVersionId()).orElseThrow();var policy=policies.findById(version.getPolicyId()).orElseThrow();var catalog=services.findById(value.getServiceId()).orElseThrow();var environment=environments.findById(value.getEnvironmentId()).orElseThrow();var requester=users.findById(value.getRequestedBy()).orElseThrow();var artifact=artifacts.findByReleaseId(id).orElseThrow();return new Detail(item(value),value.getChangeSummary(),value.getCommitSha(),value.getPipelineUrl(),artifact.getImageRepository(),new NamedContext(catalog.getName(),environment.getName()),new RequesterSummary(requester.getDisplayName(),requester.getUsername()),new SnapshotSummary(snapshot.getSourcePolicyVersionId(),policy.getName(),snapshot.getChecksum(),json.readTree(snapshot.getDefinition())),decisions.findByReleaseId(id).orElse(null));}
 private boolean allowed(Release value,Authentication auth){var catalog=services.findById(value.getServiceId()).orElse(null);return catalog!=null&&access.canView(catalog.getProjectId(),auth);}
 private Item item(Release value){return new Item(value,artifacts.findByReleaseId(value.getId()).orElseThrow().getImageDigest());}private NotFoundException notFound(){return new NotFoundException("RELEASE_NOT_FOUND","Release not found");}
 public record Item(Release release,String imageDigest){}public record NamedContext(String serviceName,String environmentName){}public record RequesterSummary(String displayName,String username){}public record SnapshotSummary(UUID sourcePolicyVersionId,String name,String checksum,JsonNode definition){}public record Detail(Item item,String changeSummary,String commitSha,String pipelineUrl,String imageRepository,NamedContext context,RequesterSummary requester,SnapshotSummary policySnapshot,ApprovalDecision approval){}
}
